# Generated by Django 3.2.1 on 2021-06-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atapp', '0002_auto_20210608_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ф.И.О.')),
                ('degree', models.CharField(max_length=150, verbose_name='Учёное степень')),
                ('rank', models.CharField(max_length=150, verbose_name='Ученые звание')),
                ('email', models.EmailField(max_length=150, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Учителя',
                'verbose_name_plural': 'Учители',
            },
        ),
    ]
