# Generated by Django 3.2.1 on 2021-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atapp', '0003_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='degree',
            field=models.CharField(blank=True, max_length=150, verbose_name='Учёное степень'),
        ),
    ]
