# Generated by Django 3.2.1 on 2021-06-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atapp', '0005_auto_20210608_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ф.И.О.')),
                ('email', models.EmailField(max_length=150, verbose_name='Электронная почта')),
                ('desc', models.CharField(max_length=1000, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Oбратная связь',
                'verbose_name_plural': 'Oбратная связь',
            },
        ),
    ]
