# Generated by Django 3.2.1 on 2021-06-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atapp', '0006_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBack',
            new_name='FeedBackViews',
        ),
    ]
