# Generated by Django 3.2.1 on 2021-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atapp', '0008_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table',
            field=models.FileField(max_length=10000, upload_to='documats/table/%Y/%m/%d/', verbose_name='График'),
        ),
    ]
