# Generated by Django 3.2.1 on 2021-06-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atapp', '0009_alter_table_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
